//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQCheckpoint2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int app_id { get; set; }
        public string app_first_name { get; set; }
        public string app_last_name { get; set; }
        public string app_address { get; set; }
        public string app_city { get; set; }
        public string app_province { get; set; }
        public string app_postal_code { get; set; }
        public string app_phone { get; set; }
        public string app_email { get; set; }
        public string app_comments { get; set; }
        public Nullable<System.DateTime> app_submission_date { get; set; }
        public Nullable<int> job_posting { get; set; }
    
        public virtual Job_Postings Job_Postings { get; set; }
    }
}
