//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQCheckpoint2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecard
    {
        public int id { get; set; }
        public string sender_first_name { get; set; }
        public string sender_last_name { get; set; }
        public string sender_email { get; set; }
        public int person_id { get; set; }
        public int card_choice { get; set; }
        public string card_message { get; set; }
    
        public virtual card_choices card_choices { get; set; }
        public virtual person person { get; set; }
    }
}
