//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FAQCheckpoint2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int ev_id { get; set; }
        public string ev_title { get; set; }
        public string ev_description { get; set; }
        public Nullable<System.DateTime> ev_start_date { get; set; }
        public Nullable<System.DateTime> ev_end_date { get; set; }
    }
}
