

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAQCheckpoint2.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class aqsmalhotraEntities : DbContext
{
    public aqsmalhotraEntities()
        : base("name=aqsmalhotraEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<Article> Articles { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Department> Departments { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<Staff_Members> Staff_Members { get; set; }

    public virtual DbSet<card_choices> card_choices { get; set; }

    public virtual DbSet<ecard> ecards { get; set; }

    public virtual DbSet<person> persons { get; set; }

}

}

