
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAQCheckpoint2.Models
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class person
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public person()
    {

        this.ecards = new HashSet<ecard>();

        this.Users = new HashSet<User>();

    }


    public int id { get; set; }

    public string first_name { get; set; }

    public string middle_name { get; set; }

    public string last_name { get; set; }
    
    [EmailAddress]
    public string email { get; set; }
 
    public string gender { get; set; }

    public string health_card { get; set; }
    
    [DataType(DataType.Date)]
    public DateTime date_of_birth { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ecard> ecards { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<User> Users { get; set; }

}

}
