
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FAQCheckpoint2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Staff_Members
{

    public int Id { get; set; }

    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public string Breaf_Bio { get; set; }

    public System.DateTime Working_From { get; set; }

    public System.DateTime Created_At { get; set; }

    public string Image_Url { get; set; }

    public int Department_Id { get; set; }



    public virtual Department Department { get; set; }

}

}
